// Generates src/registry.ts from src/lessons/**/*.mdx, inlining each lesson's
// raw MDX source as a string. Run via `pnpm --filter @visualdsa/content build`.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const lessonsDir = join(root, 'src', 'lessons');
const outFile = join(root, 'src', 'registry.ts');

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith('.mdx')) out.push(full);
  }
  return out;
}

const files = walk(lessonsDir).sort();
const entries = files.map((file) => {
  const rel = relative(lessonsDir, file)
    .split(/[\\/]/)
    .join('/')
    .replace(/\.mdx$/, '');
  const content = readFileSync(file, 'utf8');
  return `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`;
});

const output = `// AUTO-GENERATED by scripts/build.mjs from src/lessons/**/*.mdx — do not edit.
export const lessonRaw: Record<string, string> = {
${entries.join('\n')}
};
`;

writeFileSync(outFile, output);
console.info(
  `Generated ${relative(root, outFile)} with ${entries.length} lessons`,
);
